//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Гибет41размер
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gibet41Entities : DbContext
    {
        private static Gibet41Entities _context;
        public static Gibet41Entities GetContext()
        {
            if (_context == null)
                _context = new Gibet41Entities();
            return _context;
        }
        public Gibet41Entities()
            : base(@"metadata=res://*/Gibet41Model.csdl|res://*/Gibet41Model.ssdl|res://*/Gibet41Model.msl;provider=System.Data.SqlClient;provider connection string='data source=LAPTOP-72PUJMKK;initial catalog=Gibet41;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework'")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderProduct> OrderProduct { get; set; }
        public virtual DbSet<PickUpPoint> PickUpPoint { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
